apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 30s
    spec:
      containers:
        - image: docker.io/kiemtcb/detection-object:4.2x86@sha256:326e47e0290094fcfe71e14674173b156bac7e12d211051d77c6e78d37a55d04
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: mec